/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nmhieu (https://sketchfab.com/nmhieu081099)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-sofa-184617f2b5a743bda046d4760d7a8337
Title: Cartoon Sofa
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Armchair(props) {
    const { nodes, materials } = useGLTF("models/armchair.glb");
    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.sofa_lambert3_0.geometry}
                    material={materials.lambert3}
                    position={[1418.751, -32.44, -799.196]}
                    rotation={[0, -Math.PI / 2, 0]}
                    scale={64.867}
                />
            </group>
        </group>
    );
}

useGLTF.preload("models/armchair.glb");