/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: GeniusPilot2016 (https://sketchfab.com/GeniusPilot2016)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-laptop-800e9be65a78484f8193c4bfbc318b3b
Title: Gaming Laptop
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Laptop(props) {
    const { nodes, materials } = useGLTF("models/laptop.glb");
    return (
        <group {...props} dispose={null}>
            <group
                position={[0.411, 0.033, 0.621]}
                rotation={[1.745, 0, 0]}
                scale={0.123}
            >
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_4.geometry}
                    material={materials.body}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_5.geometry}
                    material={materials.display}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_6.geometry}
                    material={materials.patterns}
                />
            </group>
            <group position={[0.411, 0.03, 0.334]} scale={0.123}>
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_8.geometry}
                    material={materials.body}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_9.geometry}
                    material={materials.touchpad}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_10.geometry}
                    material={materials.metal}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_11.geometry}
                    material={materials.blue_plastic}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_12.geometry}
                    material={materials.jacks}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_13.geometry}
                    material={materials.type_c}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_14.geometry}
                    material={materials.holes_1}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_15.geometry}
                    material={materials.holes_2}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_16.geometry}
                    material={materials.patterns}
                />
            </group>
            <group position={[0.683, 0.028, 0.383]} scale={0.123}>
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_18.geometry}
                    material={materials.material}
                />
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Object_19.geometry}
                    material={materials.backlight}
                />
            </group>
        </group>
    );
}

useGLTF.preload("models/laptop.glb");